// Tokens derivados exactamente de docs/frontend/03-sistema-diseno.md
// (YAML "Institutional Excellence", aprobado 2026-08-07). No modificar
// estos valores sin actualizar ese documento primero.
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface': '#191c1d',
        'on-tertiary-container': '#f0f7ff',
        outline: '#936e69',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#f0f1f2',
        'primary-fixed': '#ffdad5',
        'surface-container': '#edeeef',
        'primary-fixed-dim': '#ffb4aa',
        'secondary-fixed-dim': '#c3c7cc',
        'inverse-surface': '#2e3132',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#c0000c',
        'outline-variant': '#e9bcb6',
        'surface-bright': '#f8f9fa',
        'surface-dim': '#d9dadb',
        'on-surface-variant': '#5e3f3b',
        'tertiary-container': '#69727a',
        'inverse-primary': '#ffb4aa',
        'secondary-fixed': '#e0e3e8',
        'surface-container-low': '#f3f4f5',
        tertiary: '#515a61',
        'on-secondary-fixed': '#181c20',
        'on-tertiary-fixed': '#141d23',
        'surface-container-highest': '#e1e3e4',
        'on-primary-container': '#fff5f3',
        'on-background': '#191c1d',
        primary: '#b5000b',
        surface: '#f8f9fa',
        'on-primary': '#ffffff',
        background: '#f8f9fa',
        'on-error-container': '#93000a',
        'on-secondary-container': '#5f6368',
        'surface-variant': '#e1e3e4',
        'tertiary-fixed': '#dbe4ed',
        'on-primary-fixed-variant': '#930007',
        'surface-container-high': '#e7e8e9',
        error: '#ba1a1a',
        'primary-container': '#e30613',
        'error-container': '#ffdad6',
        secondary: '#5b5f63',
        'on-error': '#ffffff',
        'secondary-container': '#dde0e5',
        'on-primary-fixed': '#410001',
        'on-secondary-fixed-variant': '#43474c',
        'on-tertiary-fixed-variant': '#3f484f',
        'tertiary-fixed-dim': '#bfc8d0',
        'on-tertiary': '#ffffff',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '24px',
        'margin-desktop': '64px',
        lg: '48px',
        base: '8px',
        gutter: '24px',
        xl: '80px',
        'margin-mobile': '16px',
        sm: '12px',
        xs: '4px',
      },
      fontFamily: {
        'headline-md': ['Public Sans'],
        'label-md': ['Public Sans'],
        'display-lg': ['Public Sans'],
        'label-sm': ['Public Sans'],
        'body-lg': ['Public Sans'],
        'headline-lg': ['Public Sans'],
        'body-md': ['Public Sans'],
        'headline-lg-mobile': ['Public Sans'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
